// Generates src/ui/icons.generated.ts from @material-symbols/svg-400 (Apache-2.0), rounded style.
// Usage: node scripts/generate-icons.mjs <path-to-extracted-package>/rounded
// The UI uses SVG paths instead of the variable icon font so filled/outlined variants render reliably in React Native.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const dir = process.argv[2];
if (!dir) throw new Error('Pass the path to the "rounded" directory of @material-symbols/svg-400');

const names = `add add_comment arrow_back auto_awesome call call_split check check_circle chevron_right close
description emergency inbox info keyboard location_on lock memory mic near_me play_arrow play_circle route science
search shield signal_cellular_alt sos south translate unfold_more verified_user vibration warning wifi_off
account_tree alt_route badge block delete devices directions_run directions_walk do_not_disturb_on done_all
edit_note expand_less expand_more family_restroom favorite folder_managed forward graphic_eq group group_add
groups help history home hourglass_top hub link link_off more_horiz offline_bolt pan_tool person policy
progress_activity radar replay restart_alt schedule schedule_send send sensors settings shield_person smartphone
tag task_alt timer verified visibility volunteer_activism wifi work cell_tower error my_location support_agent
qr_code_2 key bluetooth_searching cloud_off stop volume_up content_copy lock_open`.split(/\s+/).filter(Boolean);

// Icons renamed upstream since the design was drawn: design name -> current package name.
const ALIASES = {
  auto_awesome: 'wand_stars',
  expand_less: 'keyboard_arrow_up',
  expand_more: 'keyboard_arrow_down',
  offline_bolt: 'bolt',
  smartphone: 'mobile',
  vibration: 'mobile_vibrate',
};

const pathOf = (file) => {
  const svg = readFileSync(file, 'utf8');
  const d = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]).join(' ');
  if (!d) throw new Error(`No path in ${file}`);
  return d;
};

const missing = [];
const lines = [];
for (const name of [...new Set(names)].sort()) {
  const source = ALIASES[name] ?? name;
  const outline = join(dir, `${source}.svg`);
  const fill = join(dir, `${source}-fill.svg`);
  if (!existsSync(outline)) {
    missing.push(name);
    continue;
  }
  const o = pathOf(outline);
  const f = existsSync(fill) ? pathOf(fill) : o;
  lines.push(`  ${name}: { o: '${o}', f: ${f === o ? 'null' : `'${f}'`} },`);
}
if (missing.length) console.warn('Missing icons:', missing.join(', '));

writeFileSync(
  'src/ui/icons.generated.ts',
  `// GENERATED by scripts/generate-icons.mjs. Do not edit by hand.
// Source: Material Symbols Rounded (weight 400), Google, Apache License 2.0. viewBox "0 -960 960 960".
export const ICONS = {
${lines.join('\n')}
} as const satisfies Record<string, { o: string; f: string | null }>;

export type IconName = keyof typeof ICONS;
`,
);
console.log(`Wrote ${lines.length} icons`);
